
###服务启动端口号
server:
  port: 9500
###服务名称(服务注册到eureka名称)
spring:
  application:
    name:  app-fish-auth

###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1ms
###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fish_gateway?useUnicode=true&characterEncoding=UTF-8
####打印MyBatias日志
logging:
  level:
  ### 开发环境使用DEBUG 生产环境info或者error
    com.alen.auth.mapper: DEBUG
###多线程配置
threadPool:
###核心线程数
   corePoolSize: 10
 ###最大线程数
   maxPoolSize: 20
 ##  队列容量
   queueCapacity: 16


